### ISSUE TITLE
forward() missing 2 required positional arguments: 'x_left' and 'x_right'

### ISSUE THREAD

**Issue by cunese0666** [LongguangWang/PAM#3]
Mr Wang,
    I'm very interested in your work.But I have some problems in training with sceneflow dataset.
    In the process of debugging with multiple GPUs, when debugging with two GPUs, 
    if the batchsize is set to 1, "TypeError: forward() missing 2 required positional arguments: 'x_left' and 'x_right'".
    if the batchsize is set to 2, "RuntimeError: CUDA error: out of memory".
    How to solve it?

**Comment by cunese0666** [comment]
And if I directly use the pre-training model to fine-tune with kitti, there will be an error:
Traceback (most recent call last):
  File "finetune.py", line 151, in <module>
    main(cfg)
  File "finetune.py", line 147, in main
    train(train_loader, cfg)
  File "finetune.py", line 56, in train
    net.module.load_state_dict(ckpt['state_dict'])
KeyError: 'state_dict'

**Comment by LongguangWang** [comment]
Hi @cunese0666 , thanks for your interests in our work and sorry for the late response.

1. When the batchsize is set to 1, please modify the code `net = nn.DataParallel(net, device_ids=[0, 1])` (L41 in train.py) to use only one GPU. 
2. This bug has been fixed. Please try it.
